# Numpy Çalışma

### NumPy Array'i Oluşturmak

In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.5'

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [7]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [ ]:
# sifirdan array olusturma (np.zeros)

In [9]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros(10, dtype = float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# birlerden array olusturma (np.ones)

In [11]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
np.ones(10, dtype = float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# belirlenen değerler ile doldurma (np.full)

In [12]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [13]:
# code here (arange)

np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [14]:
# code here (linspace)

np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
# code here (random.normal)

np.random.normal(10, 4, (3,4))

array([[ 7.95311755, 18.88626347,  6.68342754,  9.41779354],
       [ 6.56580837,  9.3286982 ,  2.81822871, 11.70010496],
       [15.3764241 ,  8.20890978,  8.67603323,  5.88175198]])

In [16]:
# code here (random.randint)

np.random.randint(0,10, (3,3))

array([[9, 0, 2],
       [1, 1, 2],
       [5, 7, 8]])

# Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [1]:
import numpy as np

In [2]:
# code here(random.randint, hihg=10, size=10)

np.random.randint(10, size = 10)

array([8, 1, 0, 6, 3, 8, 2, 2, 8, 1])

In [3]:
a = np.random.randint(10, size = 10)

In [4]:
# code here (find the dimension of a)

a.ndim

1

In [5]:
# code here (find the shape of a)

a.shape

(10,)

In [6]:
# code here (find the size of a)

a.size

10

In [7]:
# code here (find the dtype of a)

a.dtype

dtype('int64')

In [8]:
b = np.random.randint(10, size = (3,5))

In [9]:
b

array([[5, 2, 8, 5, 8],
       [2, 4, 8, 4, 3],
       [9, 0, 2, 0, 2]])

In [11]:
# code here (find the dimension of b)

b.ndim

2

In [12]:
# code here (find the shape of b)

b.shape

(3, 5)

In [13]:
# code here (find the size of b)

b.size

15

In [14]:
# code here (find the dtype of b)

b.dtype

dtype('int64')

# Yeniden Şekillendirme (Reshaping)

In [10]:
import numpy as np

In [11]:
# code here (find the dtype of b)

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# code here (reshape (3,3) your coding above)

np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a = np.arange(1,10)

In [14]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# code here (find the dimension of a)

a.ndim

1

In [16]:
# code here (reshape a as (1,9) and assign to b)

b = a.reshape((1,9))
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
# code here (find the dimension of b)

b.ndim

2

# Array Birlestirme (Concatenation)

In [18]:
import numpy as np

In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [20]:
# code here (concatenate x and y)

np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [21]:
z = np.array([7,8,9])

In [22]:
# code here (concatenate x, y and z)

np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# code here (concatenate z, y and x)

np.concatenate([z, x, y])

array([7, 8, 9, 1, 2, 3, 4, 5, 6])

In [ ]:
#iki boyut

In [7]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [8]:
# code here (concatenate a and a)

np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [10]:
# code here (concatenate a and a)

np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,99,99,3,2,1])

In [ ]:
# code here (split x from 3 and 5)

np.split(x, [3,5])

In [4]:
# code here (do a tuple unpacking for above splitting in order of a,b,c)

a,b,c = np.split(x, [3,5])

In [5]:
a

array([1, 2, 3])

In [6]:
b

array([99, 99])

In [7]:
c

array([3, 2, 1])

In [ ]:
#iki boyutlu ayırma

In [8]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
# code here (split m)

np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [10]:
ust, alt = np.vsplit(m, [2])

In [11]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
# code here (split m)

np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [15]:
sag, sol = np.hsplit(m, [2])

In [16]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [17]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [ ]:
# code here (sort v)

np.sort(v)

In [5]:
v

array([2, 1, 4, 3, 5])

In [6]:
# code here (sort v)

v.sort()

In [7]:
v

array([1, 2, 3, 4, 5])

In [ ]:
#iki boyutlu array siralama

In [10]:
m = np.random.normal(20,5, (3,3))

In [11]:
m

array([[25.45684489, 21.83575476, 26.06913773],
       [17.50480621, 18.65456644, 25.99114299],
       [15.28755765, 21.08674903, 16.10947821]])

In [12]:
# code here (sort m)

np.sort(m, axis = 1)

array([[21.83575476, 25.45684489, 26.06913773],
       [17.50480621, 18.65456644, 25.99114299],
       [15.28755765, 16.10947821, 21.08674903]])

In [13]:
# code here (sort m)

np.sort(m, axis = 0)

array([[15.28755765, 18.65456644, 16.10947821],
       [17.50480621, 21.08674903, 25.99114299],
       [25.45684489, 21.83575476, 26.06913773]])

# Index ile Elemanlara Erişmek

In [24]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([0, 9, 7, 8, 0, 5, 9, 7, 4, 6])

In [25]:
# code here

a[0]

0

In [26]:
# code here

a[-1]

6

In [27]:
a[2], a[5], a[9] = [4, 0, 100]

In [28]:
a

array([  0,   9,   4,   8,   0,   0,   9,   7,   4, 100])

In [29]:
# code here

a[2]

4

In [30]:
# code here

a[5]

0

In [31]:
# code here

a[9]

100

In [32]:
m = np.random.randint(10, size = (3,5))
m

array([[7, 4, 2, 2, 3],
       [9, 1, 4, 4, 7],
       [2, 5, 0, 9, 8]])

In [33]:
# code here

m[0,0]

7

In [9]:
# code here

m[1,1]

3

In [10]:
# code here

m[1, 4]

9

In [34]:
# code here (look at the below array)

m[1, 4] = 99

In [35]:
m

array([[ 7,  4,  2,  2,  3],
       [ 9,  1,  4,  4, 99],
       [ 2,  5,  0,  9,  8]])

In [36]:
# code here (look at the below array)

m[1,4] = 2.2

In [37]:
m

array([[7, 4, 2, 2, 3],
       [9, 1, 4, 4, 2],
       [2, 5, 0, 9, 8]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [38]:
import numpy as np

In [39]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
# code here (look at the below array)

a[0:3]

array([20, 21, 22])

In [41]:
# code here (look at the below array)

a[:3]

array([20, 21, 22])

In [5]:
# code here (look at the below array)

a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [6]:
# code here (look at the below array)

a[1::2]

array([21, 23, 25, 27, 29])

In [7]:
# code here (look at the below array)

a[0::2]

array([20, 22, 24, 26, 28])

In [8]:
# code here (look at the below array)

a[2::2]

array([22, 24, 26, 28])

In [9]:
# code here (look at the below array)

a[0::3]

array([20, 23, 26, 29])

In [ ]:
#iki boyutlu slice islemleri

In [42]:
m = np.random.randint(10, size = (5,5))

In [43]:
m

array([[5, 5, 2, 4, 9],
       [7, 8, 4, 1, 4],
       [4, 0, 4, 9, 7],
       [1, 2, 2, 2, 4],
       [1, 2, 2, 1, 9]])

In [12]:
# code here (look at the below array)

m[:,0]

array([4, 0, 8, 3, 6])

In [13]:
# code here (look at the below array)

m[:,1]

array([9, 4, 2, 3, 4])

In [14]:
# code here (look at the below array)

m[:,4]

array([7, 5, 3, 1, 0])

In [16]:
m

array([[4, 9, 9, 8, 7],
       [0, 4, 7, 4, 5],
       [8, 2, 7, 6, 3],
       [3, 3, 8, 8, 1],
       [6, 4, 0, 5, 0]])

In [15]:
# code here (look at the below array)

m[0,:]

array([4, 9, 9, 8, 7])

In [17]:
# code here (look at the below array)

m[0]

array([4, 9, 9, 8, 7])

In [18]:
# code here (look at the below array)

m[1,:]

array([0, 4, 7, 4, 5])

In [19]:
# code here (look at the below array)

m[0:2, 0:3]

array([[4, 9, 9],
       [0, 4, 7]])

In [22]:
# code here (look at the below array)

m[:,0:2]

array([[4, 9],
       [0, 4],
       [8, 2],
       [3, 3],
       [6, 4]])

In [44]:
m

array([[5, 5, 2, 4, 9],
       [7, 8, 4, 1, 4],
       [4, 0, 4, 9, 7],
       [1, 2, 2, 2, 4],
       [1, 2, 2, 1, 9]])

In [23]:
# code here (look at the below array)

m[1:3, 0:2]

array([[0, 4],
       [8, 2]])

# Alt Küme Üzerinde İşlem Yapmak

In [47]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[7, 1, 9, 3, 9],
       [8, 0, 1, 3, 2],
       [4, 5, 5, 7, 6],
       [4, 2, 4, 5, 4],
       [6, 0, 8, 6, 6]])

In [48]:
# code here (look at the below array)

alt_a = a[0:3, 0:2]
alt_a

array([[7, 1],
       [8, 0],
       [4, 5]])

In [49]:
# code here (look at the below array)

alt_a[0,0] = 99999
alt_a[1,1] = 888

In [50]:
alt_a

array([[99999,     1],
       [    8,   888],
       [    4,     5]])

In [51]:
a

array([[99999,     1,     9,     3,     9],
       [    8,   888,     1,     3,     2],
       [    4,     5,     5,     7,     6],
       [    4,     2,     4,     5,     4],
       [    6,     0,     8,     6,     6]])

In [52]:
m = np.random.randint(10, size = (5, 5))
m

array([[6, 9, 0, 4, 6],
       [6, 5, 8, 1, 5],
       [1, 8, 6, 9, 1],
       [2, 2, 7, 4, 7],
       [9, 0, 4, 5, 1]])

In [8]:
# code here (look at the below array)

alt_b = m[0:3, 0:2].copy()
alt_b

array([[0, 5],
       [1, 7],
       [3, 2]])

In [9]:
# code here (look at the below array)

alt_b[0,0] = 9999

In [10]:
alt_b

array([[9999,    5],
       [   1,    7],
       [   3,    2]])

In [11]:
m

array([[0, 5, 2, 6, 8],
       [1, 7, 8, 7, 7],
       [3, 2, 1, 1, 9],
       [5, 0, 9, 2, 8],
       [4, 4, 6, 0, 7]])

# Fancy Index ile Elemanlara Erişmek

In [54]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [55]:
# code here

v[1]

3

In [56]:
# code here

v[3]

9

In [57]:
# code here

v[5]

15

In [58]:
# code here

[v[1], v[3], v[5]]

[3, 9, 15]

In [59]:
al_getir = [1,3,5]

In [60]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [61]:
# code here

v[al_getir]

array([ 3,  9, 15])

In [62]:
#iki boyutta fancy

In [63]:
m = np.arange(9).reshape((3,3))

In [64]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [66]:
m[satir, sutun]

array([1, 5])

In [67]:
#basit index ile fancy index

In [68]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
m[0, [1,2]]

array([1, 2])

In [70]:
#slice ile fancy

In [71]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [72]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [73]:
v < 3

array([ True,  True, False, False, False])

In [74]:
# code here

v[v < 3]

array([1, 2])

In [75]:
# code here

v[v > 3]

array([4, 5])

In [76]:
# code here

v[v >= 3]

array([3, 4, 5])

In [77]:
# code here

v[v <= 3]

array([1, 2, 3])

In [78]:
# code here

v[v == 3]

array([3])

In [79]:
# code here

v[v != 3]

array([1, 2, 4, 5])

In [80]:
v

array([1, 2, 3, 4, 5])

In [11]:
# code here

v * 2

array([ 2,  4,  6,  8, 10])

In [12]:
# code here

v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [14]:
# code here

v**2

array([ 1,  4,  9, 16, 25])

# Matematiksel İşlemler

Bu bölüm bilgi ve tekrar maksatlı konulmuştur.

In [1]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [2]:
v - 1

array([0, 1, 2, 3, 4])

In [3]:
v * 5

array([ 5, 10, 15, 20, 25])

In [4]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [5]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [ ]:
#ufunc

In [6]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [7]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [8]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [9]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [10]:
v**2

array([ 1,  4,  9, 16, 25])

In [11]:
v**3

array([  1,   8,  27,  64, 125])

In [12]:
np.power(v, 3)

array([  1,   8,  27,  64, 125])

In [13]:
v % 2

array([1, 0, 1, 0, 1])

In [14]:
np.mod(v, 2)

array([1, 0, 1, 0, 1])

In [16]:
np.absolute(np.array([-3]))

array([3])

In [20]:
np.sin(360)

0.9589157234143065

In [21]:
np.cos(180)

-0.5984600690578581

In [22]:
v = np.array([1,2,3])

In [23]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [24]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [25]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [26]:
?np

Type:        module
String form: <module 'numpy' from '/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
File:        /anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

U

In [ ]:
#cheatsheet

# İstatistiksel Hesaplamalar

In [28]:
v

array([1, 2, 3])

In [29]:
np.mean(v)

2.0

In [30]:
v.sum()

6

In [31]:
v.min()

1

* np.mean(arr,axis=0) | Returns mean along specific axis

* arr.sum() | Returns sum of arr

* arr.min() | Returns minimum value of arr

* arr.max(axis=0) | Returns maximum value of specific axis

* np.var(arr) | Returns the variance of array

* np.std(arr,axis=1) | Returns the standard deviation of specific axis

* arr.corrcoef() | Returns correlation coefficient of array

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [2]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [3]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [4]:
a

array([[5, 1],
       [1, 3]])

In [5]:
b

array([12, 10])

In [6]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])