# Pandas Çalışma

In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [3]:
## Ignore Warnings
import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")

## Pandas Serisi Oluşturmak

In [4]:
import pandas as pd 

In [5]:
pd.__version__

'1.3.4'

In [6]:
S=pd.Series({0:10, 1:88, 2:3, 3:4, 4:5})
S

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [7]:
# CODE HERE to make a PANDAS SERIE to get the output shown below.

S=pd.Series({0:10, 1:88, 2:3, 3:4, 4:5})
S

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [8]:
# CODE HERE to get the TYPE

type(S)

pandas.core.series.Series

In [9]:
# CODE HERE to get the AXES

S.axes

[Int64Index([0, 1, 2, 3, 4], dtype='int64')]

In [10]:
# CODE HERE to get the DTYPE

S.dtype

dtype('int64')

In [11]:
# CODE HERE to get the SIZE
S.size


5

In [12]:
# CODE HERE to get the DIMENSION
S.ndim


1

In [13]:
# CODE HERE to get the VALUES
S.values


array([10, 88,  3,  4,  5], dtype=int64)

In [14]:
# CODE HERE to get the FIRST 3 ROW
S.head(3)


0    10
1    88
2     3
dtype: int64

In [15]:
# CODE HERE to get the LAST 3 ROW
S.tail(3)


2    3
3    4
4    5
dtype: int64

## İndex İsimlendirmesi

In [16]:
S=pd.Series({0:99, 1:22, 2:332, 3:94, 4:5})
S

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [17]:
S2=pd.Series([99,22,332,94,5])
S2

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [18]:
S=pd.Series({1:99, 3:22, 5:332, 7:94, 9:5})
S

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [19]:
# CODE HERE

In [20]:
S=pd.Series({"a":99, "b":22, "c":332, "d":94, "e":5})
S

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [21]:
# CODE HERE

In [22]:
# CODE HERE to assign pandas serie to 'seri' 

In [23]:
seri = S

In [24]:
seri["a"]

99

In [25]:
# CODE HERE

seri["a"]

99

In [26]:
seri.head(3)

a     99
b     22
c    332
dtype: int64

In [27]:
# CODE HERE

## Sözlük Üzerinden Liste Olusturmak

In [28]:
sozluk = {"reg":10, "log":11, "cart": 12}

In [29]:
A = pd.Series(sozluk)
A

reg     10
log     11
cart    12
dtype: int64

In [30]:
# CODE HERE

In [31]:
seri = A
seri

reg     10
log     11
cart    12
dtype: int64

In [32]:
# CODE HERE to assign pandas serie to 'seri' 

In [33]:
seri.append(seri)

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

In [34]:
# CODE HERE

## Eleman İşlemleri

In [35]:
import numpy as np
a = np.array([1,2,33,444,75])
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [36]:
seri[0]

1

In [37]:
# CODE HERE

In [38]:
seri.head(3)

0     1
1     2
2    33
dtype: int32

In [39]:
# CODE HERE

In [40]:
# CODE HERE to get the OUTPUT in the below cell
seri = pd.Series({"reg":10, "log":11, "cart": 12, "rf":99})
seri

reg     10
log     11
cart    12
rf      99
dtype: int64

In [41]:
seri

reg     10
log     11
cart    12
rf      99
dtype: int64

In [42]:
seri.keys()

Index(['reg', 'log', 'cart', 'rf'], dtype='object')

In [43]:
# CODE HERE

In [44]:
seri = pd.Series({"reg":121, "loj":200, "cart": 150, "rf":99})
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [45]:
# CODE HERE

In [46]:
list(zip(seri.index,seri))

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [47]:
# CODE HERE

In [48]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [49]:
d = pd.array(seri.values)
d

<IntegerArray>
[121, 200, 150, 99]
Length: 4, dtype: Int64

## Eleman Sorgulama

In [50]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [51]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [100]:
seri.dtype == int

False

In [93]:
seri.keys == int

False

In [54]:
seri.values[0] == int

False

In [55]:
# CODE HERE

In [56]:
# CODE HERE
seri.values[0]

121

## Fancy Eleman

In [57]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [58]:
seri[[3,0]]

rf      99
reg    121
dtype: int64

In [59]:
# CODE HERE

In [60]:
# CODE HERE to get the OUTPUT in the below cell
seri = seri.replace(to_replace = 121, value = 130)
seri

reg     130
loj     200
cart    150
rf       99
dtype: int64

In [61]:
seri["reg"]

130

In [62]:
seri["reg"]

130

In [63]:
# CODE HERE
seri.head(2)

reg    130
loj    200
dtype: int64

## Pandas DataFrame Oluşturma

In [64]:
import pandas as pd

In [65]:
l = [1,2,39,67,90]

In [66]:
l

[1, 2, 39, 67, 90]

In [67]:
from pandas.core.frame import DataFrame
df = DataFrame(l, columns= ["degisken_ismi"])
df

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [68]:
# CODE HERE

In [69]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
df_var = DataFrame(m, columns= ["var1", "var2", "var3"])
df_var

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [71]:
# CODE HERE

## df İsimlendirme

In [72]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])

In [73]:
# CODE HERE
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [74]:
# CODE HERE to get the OUTPUT in the below cell
df = pd.DataFrame(m, columns = ["deg1","deg2","deg3"])
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [75]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [76]:
type(df)

pandas.core.frame.DataFrame

In [77]:
# CODE HERE

In [78]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [101]:
df. shape

(3, 3)

In [80]:
# CODE HERE


In [81]:
# CODE HERE


In [82]:
# CODE HERE


In [83]:
# CODE HERE


In [84]:
# CODE HERE


In [85]:
# CODE HERE


In [86]:
a = np.array([1,2,3,4,5])

In [87]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

# Eleman İşlemleri

In [88]:
import numpy as np
np.random.seed(99)
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [89]:
# CODE HERE to get the OUTPUT in the below cell


In [90]:
sozluk

{'reg': 10, 'log': 11, 'cart': 12}

In [91]:
# CODE HERE to get the OUTPUT in the below cell

df = pd.DataFrame(sozluk)
df

ValueError: If using all scalar values, you must pass an index

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE to get the OUTPUT in the below cell

df.index = ["a","b","c","d","e"]
df

In [ ]:
# CODE HERE


## Silme

In [ ]:
# CODE HERE


In [ ]:
df

In [ ]:
# CODE HERE


In [ ]:
df

## Fancy 

In [ ]:
l = ["c","e"]

In [ ]:
# CODE HERE


## Degiskenler İcin

In [ ]:
df

In [ ]:
# CODE HERE


In [ ]:
l = ["var1","var4","var2"]

In [ ]:
# CODE HERE


In [ ]:
df

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE to get the OUTPUT in the below cell


In [ ]:
df

## Degisken Silmek

In [ ]:
# CODE HERE


In [ ]:
df

In [ ]:
# CODE HERE


In [ ]:
df

In [ ]:
l = ["var1","var2"]

In [ ]:
# CODE HERE


## Gözlem ve Değişken Seçimi: loc & iloc

In [ ]:
import numpy as np
import pandas as pd
np.random.seed(42)
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

In [ ]:
#loc: tanımlandığı şekli ile seçim yapmak için kullanılır.

In [ ]:
# CODE HERE


In [ ]:
#iloc: alışık olduğumuz indeksleme mantığı ile seçim yapar.

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
df

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


# Koşullu Eleman İşlemleri

In [ ]:
import numpy as np
import pandas as pd
np.random.seed(101)
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
df

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


## Birleştirme İşlemleri

In [ ]:
import numpy as np
import pandas as pd
np.random.seed(33)
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df1

In [ ]:
# CODE HERE to get the below cell output


## concat()

In [ ]:
?pd.concat

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE to get the below cell output


In [ ]:
df2

In [ ]:
df1

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


## merge()

In [ ]:
import pandas as pd

In [ ]:
?pd.merge

In [ ]:
df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})

df1

In [ ]:
df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                    'ilk_giris': [2010, 2009, 2014, 2019]})

df2

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE to get below cell output


In [ ]:
df3

In [ ]:
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'İK'],
                    'mudur': ['Caner', 'Mustafa', 'Berkcan']})

df4

In [ ]:
# CODE HERE


In [ ]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

df5

In [ ]:
df1

In [ ]:
# CODE HERE


# Toplulaştırma ve Gruplama (Aggregation & Grouping)

Basit toplulaştırma fonksiyonları:

* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [ ]:
import seaborn as sns

In [ ]:
?sns.load_dataset

In [ ]:
df = sns.load_dataset("planets")
df.head()

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


## Gruplama İşlemleri

In [ ]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri'])
df

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
df = sns.load_dataset("planets")
df.head()

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


## İleri Toplulaştırma İşlemleri (Aggregate, filter, transform, apply)

In [ ]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

## aggregate

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


## filter

In [ ]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

In [ ]:
def filter_func(x):
    return x["degisken1"].std() > 9

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


## transform

In [ ]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

In [ ]:
# CODE HERE


In [ ]:
df_a = df.iloc[:,1:3]

In [ ]:
df_a.transform(lambda x: (x-x.mean()) / x.std())

## apply

In [ ]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


## Pivot Tablolar

In [ ]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE


In [ ]:
# CODE HERE
