In [1]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [3]:
arr_2d[2,1]

40

In [4]:
 arr_2d[:1,1:]

array([[10, 15]])

In [5]:
import numpy as np
arr = np.arange(1,6)
arr[arr>3]

array([4, 5])

In [7]:
arr_1 = np.arange(0,10)
arr_2 = arr_1 * 3
np.max(arr_2)

27

In [8]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-arr_2

array([0., 0., 0., 0., 0.])

In [9]:
arr=np.arange(1,37)
arr.shape

(36,)