In [1]:
import numpy as np

In [2]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [3]:
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [4]:
np.random.seed(101) #to get the same result everytime
np.random.rand(3)

array([0.51639863, 0.57066759, 0.02847423])

In [5]:
np.zeros(6, dtype='int')

array([0, 0, 0, 0, 0, 0])

In [6]:
np.ones(3)

array([1., 1., 1.])

array([ 0,  2,  4,  6,  8, 10])
Which code outputs the array above?

In [7]:

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

array([0., 10., 20., 30., 40.])
Which code outputs the array above?

In [8]:
np.linspace(0,40,5)

array([ 0., 10., 20., 30., 40.])

import numpy as np
np.random.randint(1,10)
Which one can not be the output?

In [9]:
import numpy as np
np.random.randint(1,10)

9

12

In [10]:
np.random.seed(42)
a=np.random.randint(10, size=10)
a

array([6, 3, 7, 4, 6, 9, 2, 6, 7, 4])

In [11]:
a.ndim # ?

1

In [12]:
b=np.random.randint(10, size=(3,5))
b.shape

(3, 5)

In [13]:
b.size

15

In [14]:
b.dtype

dtype('int32')

In [15]:
b.itemsize

4

In [16]:
x = np.array([1, 2, 3])

In [17]:
y = np.array([4, 5, 6])

In [18]:
x

array([1, 2, 3])

In [19]:
y

array([4, 5, 6])

In [20]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [21]:
x = np.array([1, 2, 3,99, 99, 3, 2, 1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [22]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [23]:
v = np.array([4, 1, 5, 2, 3])
v

array([4, 1, 5, 2, 3])

In [24]:
v.sort()

In [25]:
v

array([1, 2, 3, 4, 5])

In [26]:
arr = np.arange(0,11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arr has been created above. What is the output of arr[2:5]?

In [28]:
arr[2:5]

array([2, 3, 4])

arr = np.arange(1,8)
arr[arr>4]
What is the output?

In [29]:
arr = np.arange(1,8)
arr[arr>4]

array([5, 6, 7])

In [30]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

arr_2d has been created above. What is the output of arr_2d[0,2]?

In [31]:
arr_2d[0,2]

15

In [32]:
np.random.seed(42)
arr1=np.random.randint(1,9,9).reshape(3,3)
arr2=np.random.randint(1,9,9).reshape(3,3)
arr1

array([[7, 4, 5],
       [7, 3, 8],
       [5, 5, 7]])

In [33]:
arr2

array([[2, 3, 7],
       [3, 3, 8],
       [5, 4, 8]])

In [34]:
arr1+arr2

array([[ 9,  7, 12],
       [10,  6, 16],
       [10,  9, 15]])

In [35]:
arr1-arr2

array([[ 5,  1, -2],
       [ 4,  0,  0],
       [ 0,  1, -1]])

In [36]:
arr1/arr2

array([[3.5       , 1.33333333, 0.71428571],
       [2.33333333, 1.        , 1.        ],
       [1.        , 1.25      , 0.875     ]])

In [37]:
arr1*arr2

array([[14, 12, 35],
       [21,  9, 64],
       [25, 20, 56]])

In [38]:
np.sqrt(arr1)

array([[2.64575131, 2.        , 2.23606798],
       [2.64575131, 1.73205081, 2.82842712],
       [2.23606798, 2.23606798, 2.64575131]])

In [39]:
np.exp(arr2)

array([[   7.3890561 ,   20.08553692, 1096.63315843],
       [  20.08553692,   20.08553692, 2980.95798704],
       [ 148.4131591 ,   54.59815003, 2980.95798704]])

In [40]:
arr1.max(axis=0)

array([7, 5, 8])

In [41]:
arr1.min(axis=1)

array([4, 3, 5])

In [42]:
arr1.mean(axis=0)

array([6.33333333, 4.        , 6.66666667])

In [43]:
arr1.mean(axis=1)

array([5.33333333, 6.        , 5.66666667])

In [44]:
np.median(arr1,axis=0)

array([7., 4., 7.])

In [45]:
arr1.sum(axis=0)

array([19, 12, 20])

In [46]:
arr1.sum(axis=1)

array([16, 18, 17])

In [47]:
arr1

array([[7, 4, 5],
       [7, 3, 8],
       [5, 5, 7]])

In [48]:
arr2

array([[2, 3, 7],
       [3, 3, 8],
       [5, 4, 8]])

In [50]:
np.sin(arr1)

array([[ 0.6569866 , -0.7568025 , -0.95892427],
       [ 0.6569866 ,  0.14112001,  0.98935825],
       [-0.95892427, -0.95892427,  0.6569866 ]])

In [51]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-np.max(arr_2)

array([-4., -3., -2., -1.,  0.])

In [52]:
arr_1 = np.array([5,6,7])
arr_2 = np.array([4,5,6])
arr_1-arr_2

array([1, 1, 1])